import DefaultNavbar from '@/components/navbar'
import './globals.css'


export const metadata = {
  title: 'Testing Faces',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className="dark bg-slate-900">
        <DefaultNavbar/>
        {children}
        </body>
    </html>
  )
}
